{
 "title": "HAProxy 2.0",
 "description": "HAProxy backend servers",
 "tags": [
  "haproxy",
  "servers"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(haproxy_process_nbproc,instance)"
   },
   {
    "name": "port",
    "query": "label_values(haproxy_process_nbproc, instance)"
   },
   {
    "name": "backend",
    "label": "Backend",
    "query": "label_values(haproxy_backend_status{instance=~\"$host:$port\"}, proxy)"
   },
   {
    "name": "frontend",
    "label": "Frontend",
    "query": "label_values(haproxy_frontend_status{instance=~\"$host:$port\"}, proxy)"
   },
   {
    "name": "server",
    "label": "Server",
    "query": "label_values(haproxy_server_status{instance=~\"$host:$port\"}, server)"
   },
   {
    "name": "code",
    "label": "HTTP Code",
    "query": "label_values(haproxy_server_http_responses_total{instance=~\"$host:$port\"}, code)"
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  { "title": "Basic Backend status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(haproxy_frontend_status{instance=~\"$host:$port\"} == 1)",
     "legendFormat": "Frontends Up"
    },
    {
     "expr": "count(haproxy_backend_status{instance=~\"$host:$port\"} ==1)",
     "legendFormat": "Backends Up"
    }
   ]
  },
  {
   "title": "Basic General Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total number of HTTP responses",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(haproxy_frontend_http_responses_total{proxy=~\"$frontend\",code=~\"$code\",instance=~\"$host:$port\"}[5m])) by (code)",
       "legendFormat": "Frontend {{ code }}"
      },
      {
       "expr": "sum(irate(haproxy_backend_http_responses_total{proxy=~\"$backend\",code=~\"$code\",instance=~\"$host:$port\"}[5m])) by (code)",
       "legendFormat": "Backend {{ code }}"
      }
     ]
    },
    {
     "title": "Current total of incoming / outgoing bytes",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(irate(haproxy_frontend_bytes_in_total{proxy=~\"$frontend\",instance=~\"$host:$port\"}[5m])*8) by (instance)",
       "legendFormat": "IN Front"
      },
      {
       "expr": "sum(irate(haproxy_frontend_bytes_out_total{proxy=~\"$frontend\",instance=~\"$host:$port\"}[5m])*8) by (instance)",
       "legendFormat": "OUT Front"
      },
      {
       "expr": "sum(irate(haproxy_backend_bytes_in_total{proxy=~\"$backend\",instance=~\"$host:$port\"}[5m])*8) by (instance)",
       "legendFormat": "IN Back"
      },
      {
       "expr": "sum(irate(haproxy_backend_bytes_out_total{proxy=~\"$backend\",instance=~\"$host:$port\"}[5m])*8) by (instance)",
       "legendFormat": "OUT Back"
      }
     ]
    },
    {
     "title": "Total number of connections",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(haproxy_frontend_connections_total{proxy=~\"$frontend\",instance=~\"$host:$port\"}[5m])) by (instance)",
       "legendFormat": "Front"
      },
      {
       "expr": "sum(irate(haproxy_backend_connection_errors_total{proxy=~\"$backend\",instance=~\"$host:$port\"}[5m])) by (instance)",
       "legendFormat": "Back errors"
      }
     ]
    },
    {
     "title": "Total received requests / responses",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(haproxy_frontend_http_requests_total{proxy=~\"$frontend\",instance=~\"$host:$port\"}[5m])) by (instance)",
       "legendFormat": "Frontend requests"
      },
      {
       "expr": "sum(irate(haproxy_frontend_request_errors_total{proxy=~\"$frontend\",instance=~\"$host:$port\"}[5m])) by (instance)",
       "legendFormat": "Frontend requests errors"
      },
      {
       "expr": "sum(irate(haproxy_frontend_requests_denied_total{proxy=~\"$frontend\",instance=~\"$host:$port\"}[5m])) by (instance)",
       "legendFormat": "Frontend request denied"
      },
      {
       "expr": "sum(irate(haproxy_backend_redispatch_warnings_total{proxy=~\"$backend\",instance=~\"$host:$port\"}[5m])) by (instance)",
       "legendFormat": "Backend redispatch warnings"
      },
      {
       "expr": "sum(irate(haproxy_backend_retry_warnings_total{proxy=~\"$backend\",instance=~\"$host:$port\"}[5m])) by (instance)",
       "legendFormat": "Backend retry warnings"
      },
      {
       "expr": "sum(irate(haproxy_backend_response_errors_total{proxy=~\"$backend\",instance=~\"$host:$port\"}[5m])) by (instance)",
       "legendFormat": "Backend response errors"
      },
      {
       "expr": "sum(haproxy_backend_current_queue{proxy=~\"$backend\",instance=~\"$host:$port\"}) by (instance)",
       "legendFormat": "Backend queued requests"
      },
      {
       "expr": "sum(irate(haproxy_backend_http_requests_total{proxy=~\"$backend\",instance=~\"$host:$port\"}[5m])) by (instance)",
       "legendFormat": "Backend requests"
      }
     ]
    },
    {
     "title": "Number of active sessions",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(haproxy_frontend_current_sessions{proxy=~\"$frontend\",instance=~\"$host:$port\"}[5m])) by (instance)",
       "legendFormat": "Frontend current sessions"
      },
      {
       "expr": "sum(irate(haproxy_backend_current_sessions{proxy=~\"$frontend\",instance=~\"$host:$port\"}[5m])) by (instance)",
       "legendFormat": "Backend current sessions"
      }
     ]
    }
   ]
  },
  { "title": "Throughtput / Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Back - Total number of connections",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_backend_connection_attempts_total{proxy=~\"$backend\",instance=~\"$host:$port\"}[5m])",
     "legendFormat": "Attempts {{ proxy }}"
    },
    {
     "expr": "irate(haproxy_backend_connection_errors_total{proxy=~\"$backend\",instance=~\"$host:$port\"}[5m])",
     "legendFormat": "Error {{ proxy }}"
    }
   ]
  },
  {
   "title": "Back - Current total of incoming / outgoing bytes",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_backend_bytes_in_total{proxy=~\"$backend\",instance=~\"$host:$port\"}[5m])*8",
     "legendFormat": "IN {{ proxy }}"
    },
    {
     "expr": "irate(haproxy_backend_bytes_out_total{proxy=~\"$backend\",instance=~\"$host:$port\"}[5m])*8",
     "legendFormat": "OUT {{ proxy }}"
    }
   ]
  },
  {
   "title": "Front - Current total of incoming / outgoing bytes",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_frontend_bytes_in_total{proxy=~\"$frontend\",instance=~\"$host:$port\"}[5m])*8",
     "legendFormat": "IN {{ proxy }}"
    },
    {
     "expr": "irate(haproxy_frontend_bytes_out_total{proxy=~\"$frontend\",instance=~\"$host:$port\"}[5m])*8",
     "legendFormat": "OUT {{ proxy }}"
    }
   ]
  },
  {
   "title": "Front - Total number of connections",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_frontend_connections_total{proxy=~\"$frontend\",instance=~\"$host:$port\"}[5m])",
     "legendFormat": "Total {{ proxy }}"
    },
    {
     "expr": "irate(haproxy_frontend_denied_connections_total{proxy=~\"$frontend\",instance=~\"$host:$port\"}[5m])",
     "legendFormat": "Denied {{ proxy }}"
    }
   ]
  },
  {
   "title": "Back - Total number of connections reuses",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_backend_connection_reuses_total{proxy=~\"$backend\",instance=~\"$host:$port\"}[5m])",
     "legendFormat": "Reuses {{ proxy }}"
    }
   ]
  },
  {
   "title": "Front - Maximum observed number of connections per second",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_frontend_connections_rate_max{proxy=~\"$frontend\",instance=~\"$host:$port\"}",
     "legendFormat": "{{ proxy }}"
    }
   ]
  },
  {
   "title": "Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Back - Current number of queued requests not assigned to any server",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_backend_current_queue{proxy=~\"$backend\",instance=~\"$host:$port\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Maximum observed number of queued requests not assigned to any server",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_backend_max_queue{proxy=~\"$backend\",instance=~\"$host:$port\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Avg. queue time for last 1024 successful connections",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 80 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "haproxy_backend_http_queue_time_average_seconds{proxy=~\"$backend\",instance=~\"$host:$port\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests / Responses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Back - Total HTTP requests OK / Denied",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 81 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_backend_http_requests_total{proxy=~\"$frontend\",instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Total {{ proxy }}"
      },
      {
       "expr": "irate(haproxy_backend_requests_denied_total{proxy=~\"$frontend\", instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Denied {{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Total HTTP requests OK / Error / Denied",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 81 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_frontend_http_requests_total{proxy=~\"$frontend\",instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Total {{ proxy }}"
      },
      {
       "expr": "irate(haproxy_frontend_request_errors_total{proxy=~\"$frontend\", instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Error {{ proxy }}"
      },
      {
       "expr": "irate(haproxy_frontend_requests_denied_total{proxy=~\"$frontend\", instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Denied {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Total HTTP responses denied",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 94 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_backend_responses_denied_total{proxy=~\"$backend\", instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Denied {{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Total HTTP responses Denied",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 94 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_frontend_responses_denied_total{proxy=~\"$frontend\",instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Denied {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Total of Redispatch / Error / Retry warnings",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 107 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_backend_redispatch_warnings_total{proxy=~\"$backend\", instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Redispatch {{ proxy }}"
      },
      {
       "expr": "irate(haproxy_backend_retry_warnings_total{proxy=~\"$backend\", instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Retry {{ proxy }}"
      },
      {
       "expr": "irate(haproxy_backend_response_errors_total{proxy=~\"$backend\", instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Error {{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Maximum observed number of HTTP requests per second",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 107 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_frontend_http_requests_rate_max{proxy=~\"$backend\", instance=~\"$host:$port\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Avg. Times",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 120 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "haproxy_backend_http_connect_time_average_seconds{proxy=~\"$backend\",instance=~\"$host:$port\"}",
       "legendFormat": "Avg. connect time  {{ proxy }}"
      },
      {
       "expr": "haproxy_backend_http_response_time_average_seconds{proxy=~\"$backend\",instance=~\"$host:$port\"}",
       "legendFormat": "Avg. response time  {{ proxy }}"
      },
      {
       "expr": "haproxy_backend_http_total_time_average_seconds{proxy=~\"$backend\",instance=~\"$host:$port\"}",
       "legendFormat": "Avg. total time  {{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Responses by HTTP code",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Back - Total of HTTP responses",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 121 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_backend_http_responses_total{proxy=~\"$backend\", code=~\"$code\",instance=~\"$host:$port\"}[5m])",
       "legendFormat": "{{ code }} {{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Total of HTTP responses",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 121 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_frontend_http_responses_total{proxy=~\"$frontend\", code=~\"$code\",instance=~\"$host:$port\"}[5m])",
       "legendFormat": "{{ code }} {{ proxy }} "
      }
     ]
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "Back - Total number of sessions",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 122 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_backend_sessions_total{proxy=~\"$backend\",instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Total {{ proxy }}"
      },
      {
       "expr": "haproxy_backend_current_sessions{proxy=~\"$backend\",instance=~\"$host:$port\"}",
       "legendFormat": "Current active {{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Total number of sessions",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 122 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_frontend_sessions_total{proxy=~\"$frontend\",instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Total {{ proxy }}"
      },
      {
       "expr": "irate(haproxy_frontend_denied_sessions_total{proxy=~\"$frontend\",instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Denied by \"tcp-request session\" rules {{ proxy }}"
      },
      {
       "expr": "haproxy_frontend_current_sessions{proxy=~\"$backend\",instance=~\"$host:$port\"}",
       "legendFormat": "Current active {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Maximum observed number of active sessions and limit",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 135 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_backend_max_sessions{proxy=~\"$backend\",instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Max {{ proxy }}"
      },
      {
       "expr": "haproxy_backend_limit_sessions{proxy=~\"$backend\",instance=~\"$host:$port\"}",
       "legendFormat": "Limit {{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Maximum observed number of active sessions and limit",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 135 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_frontend_max_sessions{proxy=~\"$frontend\",instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Max {{ proxy }}"
      },
      {
       "expr": "haproxy_frontend_limit_sessions{proxy=~\"$frontend\",instance=~\"$host:$port\"}",
       "legendFormat": "Limit {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Maximum observed number of sessions per second",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 148 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_backend_max_session_rate{proxy=~\"$backend\",instance=~\"$host:$port\"}",
       "legendFormat": "Max {{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Maximum observed number of sessions per second and limit",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 148 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_frontend_max_session_rate{proxy=~\"$frontend\",instance=~\"$host:$port\"}",
       "legendFormat": "Max {{ proxy }}"
      },
      {
       "expr": "haproxy_frontend_limit_session_rate{proxy=~\"$frontend\",instance=~\"$host:$port\"}",
       "legendFormat": "Limit {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Failed header rewriting warnings",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 161 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_backend_failed_header_rewriting_total{proxy=~\"$frontend\",instance=~\"$host:$port\"}[5m])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Failed header rewriting warnings",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 161 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_frontend_failed_header_rewriting_total{proxy=~\"$frontend\",instance=~\"$host:$port\"}[5m])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back -  Last session assigned",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 174 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "haproxy_backend_last_session_seconds{proxy=~\"$frontend\",instance=~\"$host:$port\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Total HTTP Sessions Denied",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 174 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_frontend_denied_sessions_total{proxy=~\"$frontend\",instance=~\"$host:$port\"}[5m])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back -  Data transfers aborted",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 187 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "haproxy_backend_client_aborts_total{proxy=~\"$frontend\",instance=~\"$host:$port\"}",
       "legendFormat": "By client {{ proxy }}"
      },
      {
       "expr": "haproxy_backend_server_aborts_total{proxy=~\"$frontend\",instance=~\"$host:$port\"}",
       "legendFormat": "By server {{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Maximum observed number of HTTP requests per second",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 187 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_frontend_http_requests_rate_max{proxy=~\"$frontend\",instance=~\"$host:$port\"}[5m])",
       "legendFormat": "{{ proxy }} max"
      }
     ]
    }
   ]
  },
  {
   "title": "Health and Weight",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "Back - Total number of UP->DOWN transitions",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 188 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_backend_check_up_down_total{proxy=~\"$backend\", instance=~\"$host:$port\"}[5m])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Total weight of the servers in the backend / Active servers backend",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 188 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_backend_weight{proxy=~\"$backend\", instance=~\"$host:$port\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Number of seconds since last session assigned to server/backend",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 201 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_backend_last_session_seconds{proxy=~\"$backend\", instance=~\"$host:$port\"}[5m])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Total number of times a service was selected",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 201 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_backend_loadbalanced_total{proxy=~\"$backend\", instance=~\"$host:$port\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache / Compressor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Back - Cache lookups / hits",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 202 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_backend_http_cache_lookups_total{proxy=~\"$backend\", instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Lookups {{ proxy }} "
      },
      {
       "expr": "irate(haproxy_backend_http_cache_hits_total{proxy=~\"$backend\", instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Hits {{ proxy }} "
      }
     ]
    },
    {
     "title": "Front - Cache lookups / hits",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 202 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_frontend_http_cache_lookups_total{proxy=~\"$backend\", instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Lookups {{ proxy }} "
      },
      {
       "expr": "irate(haproxy_frontend_http_cache_hits_total{proxy=~\"$backend\", instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Hits {{ proxy }} "
      }
     ]
    },
    {
     "title": "Back - Compressor",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 213 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_backend_http_comp_bytes_in_total{proxy=~\"$backend\", instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Bytes fed {{ proxy }} "
      },
      {
       "expr": "irate(haproxy_backend_http_comp_bytes_out_total{proxy=~\"$backend\", instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Bytes emitted {{ proxy }} "
      },
      {
       "expr": "irate(haproxy_backend_http_comp_bytes_bypassed_total{proxy=~\"$backend\", instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Bytes bypassed  {{ proxy }} "
      }
     ]
    },
    {
     "title": "Front - Compressor",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 213 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_frontend_http_comp_bytes_in_total{proxy=~\"$backend\", instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Bytes fed {{ proxy }} "
      },
      {
       "expr": "irate(haproxy_frontend_http_comp_bytes_out_total{proxy=~\"$backend\", instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Bytes emitted {{ proxy }} "
      },
      {
       "expr": "irate(haproxy_frontend_http_comp_bytes_bypassed_total{proxy=~\"$backend\", instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Bytes bypassed  {{ proxy }} "
      }
     ]
    },
    {
     "title": "Back - Responses compressed",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 224 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_backend_http_comp_responses_total{proxy=~\"$backend\", instance=~\"$host:$port\"}[5m])",
       "legendFormat": "{{ proxy }} "
      }
     ]
    },
    {
     "title": "Front - Responses compressed",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 224 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_frontend_http_comp_responses_total{proxy=~\"$backend\", instance=~\"$host:$port\"}[5m])",
       "legendFormat": "{{ proxy }} "
      }
     ]
    }
   ]
  },
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "Back - Status",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 225 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_backend_status{proxy=~\"$backend\",instance=~\"$host:$port\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Status",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 225 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_frontend_status{proxy=~\"$frontend\",instance=~\"$host:$port\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By Server Throughtput / Connections / Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - Current total of incoming / outgoing bytes",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 226 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_server_bytes_in_total{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])*8",
       "legendFormat": "IN {{ proxy }} / {{ server }}"
      },
      {
       "expr": "irate(haproxy_server_bytes_out_total{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])*8",
       "legendFormat": "OUT {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Total number of connections",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 226 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_server_connection_attempts_total{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Attempts {{ proxy }} / {{ server }}"
      },
      {
       "expr": "irate(haproxy_server_connection_errors_total{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Error {{ proxy }} / {{ server }}"
      },
      {
       "expr": "irate(haproxy_server_connection_reuses_total{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Reuses {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Status",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 239 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_status{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Number of queued requests",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 239 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_server_current_queue{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Current {{ proxy }} / {{ server }}"
      },
      {
       "expr": "haproxy_server_queue_limit{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}",
       "legendFormat": "Limit {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Avg. queue time for last 1024 successful connections",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 252 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_server_http_queue_time_average_seconds{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By Server Requests / Responses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - Total of Retry / Error / Redispatch warnings",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 253 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_server_redispatch_warnings_total{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Redispatch {{ proxy }} / {{ server }}"
      },
      {
       "expr": "irate(haproxy_server_retry_warnings_total{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Retry {{ proxy }} / {{ server }}"
      },
      {
       "expr": "irate(haproxy_server_response_errors_total{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Error {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Back - Average times",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 253 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_http_connect_time_average_seconds{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}",
       "legendFormat": "Avg. connect time  {{ proxy }} / {{ server }}"
      },
      {
       "expr": "haproxy_server_http_response_time_average_seconds{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}",
       "legendFormat": "Avg. response time  {{ proxy }} / {{ server }}"
      },
      {
       "expr": "haproxy_server_http_total_time_average_seconds{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}",
       "legendFormat": "Avg. total time  {{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By Server Responses by HTTP code",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - Total of HTTP responses",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 254 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_server_http_responses_total{proxy=~\"$backend\",server=~\"$server\",code=~\"$code\",instance=~\"$host:$port\"}[5m])",
       "legendFormat": "{{ proxy }} {{ server }} {{ code }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By Server Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - Number of active sessions",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 255 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_server_sessions_total{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Total {{ proxy }} / {{ server }}"
      },
      {
       "expr": "haproxy_server_limit_sessions{proxy=~\"$backend\",instance=~\"$host:$port\"}",
       "legendFormat": "Limit {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Number of sessions per second and limit",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 255 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_max_session_rate{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}",
       "legendFormat": "Rate {{ proxy }} / {{ server }}"
      },
      {
       "expr": "haproxy_server_limit_session_rate{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}",
       "legendFormat": "Limit {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Failed header rewriting warnings",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 269 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_server_failed_header_rewriting_total{proxy=~\"$frontend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])",
       "legendFormat": "{{ proxy }} /  {{ server }}"
      }
     ]
    },
    {
     "title": "Server -  Data transfers aborted",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 269 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_client_aborts_total{proxy=~\"$frontend\",server=~\"$server\",instance=~\"$host:$port\"}",
       "legendFormat": "By client {{ proxy }} / {{ server }}"
      },
      {
       "expr": "haproxy_server_server_aborts_total{proxy=~\"$frontend\",server=~\"$server\",instance=~\"$host:$port\"}",
       "legendFormat": "By server {{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By Server Health / Weight",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - Total downtime in seconds",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 270 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_downtime_seconds_total{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Checks history",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 270 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "increase(haproxy_server_check_failures_total{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Total number of failed check {{ proxy }} / {{ server }}"
      },
      {
       "expr": "increase(haproxy_server_check_up_down_total{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Total number of UP->DOWN transitions {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Total of connection errors",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 284 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_server_connection_errors_total{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Throttle",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 284 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_current_throttle{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}",
       "legendFormat": "Current throttle percentage for the server, when slowstart is active, or no value if not in slowstart {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Loadbalanced",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 298 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_loadbalanced_total{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}",
       "legendFormat": "Total number of times a service was selected {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Number of seconds since last session assigned to server/backend",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 298 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_server_last_session_seconds{proxy=~\"$backend\", server=~\"$server\",instance=~\"$host:$port\"}[5m])",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Service weight",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 312 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_weight{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Process Connections / Sessions / Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process - Sessions over last second",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 313 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_current_session_rate{instance=~\"$host:$port\"}",
       "legendFormat": "Current number of sessions per second over last elapsed second"
      },
      {
       "expr": "haproxy_process_limit_session_rate{instance=~\"$host:$port\"}",
       "legendFormat": "Configured maximum number of sessions per second"
      }
     ]
    },
    {
     "title": "Process - Total sessions / requests",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 313 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_process_connections_total{instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Total number of created sessions"
      },
      {
       "expr": "irate(haproxy_process_requests_total{instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Total number of requests (TCP or HTTP)"
      }
     ]
    },
    {
     "title": "Process - Connections over last second",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 326 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_current_connection_rate{instance=~\"$host:$port\"}",
       "legendFormat": "Current number of connections per second over last elapsed second"
      },
      {
       "expr": "haproxy_process_limit_connection_rate{instance=~\"$host:$port\"}",
       "legendFormat": "Configured maximum number of connections per second."
      }
     ]
    },
    {
     "title": "Process - Connections",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 326 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_max_connections{instance=~\"$host:$port\"}",
       "legendFormat": "Maximum number of concurrent connections"
      },
      {
       "expr": "haproxy_process_hard_max_connections{instance=~\"$host:$port\"}",
       "legendFormat": "Initial Maximum number of concurrent connections"
      }
     ]
    }
   ]
  },
  {
   "title": "Process Compression",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process - Compression memory",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 327 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_current_zlib_memory{instance=~\"$host:$port\"}",
       "legendFormat": "Current memory used for zlib in bytes"
      },
      {
       "expr": "haproxy_process_max_zlib_memory{instance=~\"$host:$port\"}",
       "legendFormat": "Configured maximum amount of memory for zlib in bytes"
      }
     ]
    },
    {
     "title": "Process - Compression",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 327 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_http_comp_bytes_in_total{instance=~\"$host:$port\"}",
       "legendFormat": "Number of bytes per second over last elapsed second, before http compression"
      },
      {
       "expr": "haproxy_process_http_comp_bytes_out_total{instance=~\"$host:$port\"}",
       "legendFormat": "Number of bytes per second over last elapsed second, after http compression"
      },
      {
       "expr": "haproxy_process_limit_http_comp{instance=~\"$host:$port\"}",
       "legendFormat": "Configured maximum input compression rate in bytes"
      }
     ]
    }
   ]
  },
  {
   "title": "Process SSL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process - SSL cache",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 328 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_process_ssl_cache_lookups_total{instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Total number of SSL session cache lookups"
      },
      {
       "expr": "irate(haproxy_process_ssl_cache_misses_total{instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Total number of SSL session cache misses"
      }
     ]
    },
    {
     "title": "Process - SSL key rate",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 328 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_current_frontend_ssl_key_rate{instance=~\"$host:$port\"}",
       "legendFormat": "Current frontend SSL Key computation per second over last elapsed second"
      },
      {
       "expr": "haproxy_process_current_backend_ssl_key_rate{instance=~\"$host:$port\"}",
       "legendFormat": "Current backend SSL Key computation per second over last elapsed second"
      }
     ]
    },
    {
     "title": "Process - SSL rate",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 340 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_current_ssl_rate{instance=~\"$host:$port\"}",
       "legendFormat": "Current number of SSL sessions per second over last elapsed second"
      },
      {
       "expr": "haproxy_process_limit_ssl_rate{instance=~\"$host:$port\"}",
       "legendFormat": "Configured maximum number of SSL sessions per second"
      }
     ]
    },
    {
     "title": "Process - SSL connections",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 340 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_current_ssl_connections{instance=~\"$host:$port\"}",
       "legendFormat": "Current number of opened SSL connections"
      },
      {
       "expr": "haproxy_process_max_ssl_connections{instance=~\"$host:$port\"}",
       "legendFormat": "Configured maximum number of concurrent SSL connections"
      }
     ]
    },
    {
     "title": "Process - SSL reuse ratio",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 352 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_frontent_ssl_reuse{instance=~\"$host:$port\"}",
       "legendFormat": "SSL session reuse ratio (percent)"
      }
     ]
    }
   ]
  },
  {
   "title": "Process Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process - Memory",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 353 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_max_memory_bytes{instance=~\"$host:$port\"}",
       "legendFormat": "Per-process memory limit (in bytes); 0=unset"
      },
      {
       "expr": "irate(haproxy_process_pool_allocated_bytes{instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Total amount of memory allocated in pools (in bytes)"
      },
      {
       "expr": "irate(haproxy_process_pool_used_bytes{instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Total amount of memory used in pools (in bytes)"
      }
     ]
    },
    {
     "title": "Process - Tasks",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 353 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_process_current_tasks{instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Current number of tasks"
      },
      {
       "expr": "haproxy_process_current_run_queue{instance=~\"$host:$port\"}",
       "legendFormat": "Current number of tasks in the run-queue"
      },
      {
       "expr": "haproxy_process_stopping{instance=~\"$host:$port\"}",
       "legendFormat": "Non zero means stopping in progress"
      }
     ]
    },
    {
     "title": "Process - Maximum open files / sockets",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 365 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_max_fds{instance=~\"$host:$port\"}",
       "legendFormat": "Maximum number of open file descriptors; 0=unset"
      },
      {
       "expr": "haproxy_process_max_sockets{instance=~\"$host:$port\"}",
       "legendFormat": "Maximum numer of open sockets"
      }
     ]
    },
    {
     "title": "Process - Pipes",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 365 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_max_pipes{instance=~\"$host:$port\"}",
       "legendFormat": "Configured maximum number of pipes"
      },
      {
       "expr": "irate(haproxy_process_pipes_used_total{instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Number of pipes in used"
      },
      {
       "expr": "irate(haproxy_process_pipes_free_total{instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Number of pipes unused"
      }
     ]
    },
    {
     "title": "Process - Configured threads / processes",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 377 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_nbthread{instance=~\"$host:$port\"}",
       "legendFormat": "Threads"
      },
      {
       "expr": "haproxy_process_nbproc{instance=~\"$host:$port\"}",
       "legendFormat": "Processes"
      }
     ]
    },
    {
     "title": "Process - Pool allocations",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 377 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_pool_failures_total{instance=~\"$host:$port\"}",
       "legendFormat": "Total number of failed pool allocations"
      }
     ]
    },
    {
     "title": "Process - Idle",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 389 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_idle_time_percent{instance=~\"$host:$port\"}",
       "legendFormat": "Idle to total ratio over last sample (percent)"
      }
     ]
    },
    {
     "title": "Process - Jobs",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 389 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_process_jobs{instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Current number of active jobs (listeners, sessions, open devices)"
      },
      {
       "expr": "irate(haproxy_process_unstoppable_jobs{instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Current number of active jobs that can't be stopped during a soft stop"
      },
      {
       "expr": "irate(haproxy_process_listeners{instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Current number of active listeners"
      }
     ]
    },
    {
     "title": "Process - Peers",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 401 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_active_peers{instance=~\"$host:$port\"}",
       "legendFormat": "Current number of active peers"
      },
      {
       "expr": "haproxy_process_connected_peers{instance=~\"$host:$port\"}",
       "legendFormat": "Current number of connected peers"
      }
     ]
    },
    {
     "title": "Process - Logs",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 401 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_dropped_logs_total{instance=~\"$host:$port\"}",
       "legendFormat": "Total number of dropped logs"
      }
     ]
    }
   ]
  }
 ]
}